### ISSUE TITLE
Please don't use javax namaespace

### ISSUE THREAD

**Issue by kittylyst** [struberg/javaConfig#1]
The java & javax namespaces are reserved for definitions of accepted official Java standards.

This project looks interesting, but until it is proposed and accepted as a JSR and adopted as a true Java standard, it should not use the javax namespace. This prevents confusion among users and stops proliferation of partially complete or non-compliant code.

This is especially true in places like Giuthub where code is easily forked and divorced from its original context.

Please can you change the packages so that they don't use "javax". Perhaps something like "proposed.javax" would work for you instead?

-Ben (member of Java Community Process Executive Committee)

**Comment by struberg** [comment]
txs, moved it to my own javx namespace.
